### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by virtueDe** [virtueDe/moon-cli#1]
##  配置版本

- [x] dai

``` moon-cli --version```

## 配置help

- [x] dai

``` moon-cli --help ```

## 配置 create

- [x] dai

```shell
moon-cli createProject  name  // 新建项目模版(vue3/vue2)
moon-cli createlib  name  // 新建库/包/组件模版(rollup打包ts/rollup打包vue3 rollup打包vue2 )
```

**Comment by virtueDe** [comment]
# 二阶段 TODOLIST

- [x] 根据配置修改模版package.json 的一些信息

**Comment by virtueDe** [comment]
# 三阶段 TODOLIST

- [ ]  版本记录
- [ ] eslint + prettier 格式
- [ ] git commit 格式

**Comment by virtueDe** [comment]
# 四阶段 TODOLIST

- [ ]  模版数据不在使用常量枚举，用GitHubAPI 请求仓库分支
